<div class="grid-item-container grid-container-left-03">
      <div class="dl-01">На основу предњег налога извршио сам службено путовање и подносим следећи</div>
      <div class="prl-01"></div>
      <div class="dl-02">ПУТНИ РАЧУН</div>
      <div class="dl-03"></div>
      <div class="dl-04">Дан одласка ................ у .......... час. </div>
      <div class="dl-05">Број час.</div>
      <div class="dl-06">Број днев.</div>
      <div class="dl-07"></div>
      <div class="dl-08">По динара</div>
      <div class="dl-09">СВЕГА ДИНАРА</div>
      <div class="dl-10">Дан повратка ................ у .......... час.</div>
      <div class="dl-11"></div>
      <div class="dl-12"></div>
      <div class="dl-13"></div>
      <div class="dl-14"></div>
      <div class="dl-15"></div>
      <div class="dl-16"></div>
      <div class="dl-17"></div>
      <div class="prl-02"></div>
      <div class="dl-18">од</div>
      <div class="dl-19">до</div>
      <div class="dl-20">Врста превоза</div>
      <div class="dl-21">кл.</div>
      <div class="dl-22">динара</div>
      <div class="prl-03"></div>
      <div class="prl-04"></div>
      <div class="dl-23"></div>
      <div class="dl-24"></div>
      <div class="dl-25"></div>
      <div class="dl-26"></div>
      <div class="dl-27"></div>
      <div class="dl-28"></div>
      <div class="dl-29"></div>
      <div class="dl-30"></div>
      <div class="dl-31"></div>
      <div class="dl-32"></div>
      <div class="dl-33"></div>
      <div class="dl-34"></div>
      <div class="dl-35"></div>
      <div class="dl-36"></div>
      <div class="dl-37"></div>
      <div class="dl-38"></div>
      <div class="dl-39"></div>
      <div class="dl-40"></div>
      <div class="dl-41"></div>
      <div class="dl-42"></div>
      <div class="dl-43"></div>
      <div class="dl-44"></div>
      <div class="dl-45"></div>
      <div class="dl-46"></div>
      <div class="dl-47"></div>
      <div class="dl-48"></div>
      <div class="dl-49"></div>
      <div class="dl-50"></div>
      <div class="dl-51"></div>
      <div class="dl-52"></div>
      <div class="dl-53"></div>
      <div class="dl-54"></div>
      <div class="dl-55"></div>
      <div class="dl-56"></div>
      <div class="dl-57"></div>
      <div class="dl-58"></div>
      <div class="dl-59"></div>
      <div class="dl-60"></div>
      <div class="dl-61"></div>
      <div class="dl-62"></div>
      <div class="dl-63"></div>
      <div class="dl-64"></div>
      <div class="dl-65"></div>
      <div class="dl-66"></div>
      <div class="dl-67"></div>
      <div class="dl-68"></div>
      <div class="dl-69"></div>
      <div class="dl-70"></div>
      <div class="prl-05"></div>
      <div class="dl-71"></div>
      <div class="dl-72"></div>
      <div class="dl-73"></div>
      <div class="dl-74"></div>
      <div class="dl-75"></div>
      <div class="dl-76"></div>
      <div class="dl-77"></div>
      <div class="dl-78"></div>
      <div class="dl-79"></div>
      <div class="dl-80"></div>
      <div class="dl-81"></div>
      <div class="dl-82"></div>
      <div class="dl-83"></div>
      <div class="dl-84"></div>
      <div class="dl-85"></div>
      <div class="prl-06"></div>
      <div class="dl-86">Свега</div>
      <div class="dl-87"></div>
      <div class="dl-88"></div>
      <div class="dl-89">Примљена аконтација</div>
      <div class="dl-90"></div>
      <div class="dl-91"></div>
      <div class="prl-07"></div>
      <div class="dl-92">Број прилога:</div>
      <div class="dl-93">Остаје за исплату - уплату</div>
      <div class="dl-94"></div>
      <div class="dl-95"></div>
      <div class="dl-96">У ................................... дана ...................... 20 </div>
      <div class="prl-08"></div>
      <div class="dl-97"></div>
      <div class="prl-09"></div>
      <div class="dl-98">(подносилац рачуна) </div>
      <div class="prl-10"></div>
      <div class="dl-99">Потврђујем да је путовање извршено према овом налогу и одобравам исплату путног</div>
      <div class="prl-11"></div>
      <div class="dl-100">рачуна од динара</div>
      <div class="dl-101"></div>
      <div class="prl-12"></div>
      <div class="dl-102">Словима:</div>
      <div class="dl-103"></div>
      <div class="dl-104"></div>
      <div class="prl-13"></div>
      <div class="dl-105">на терет:</div>
      <div class="dl-106"></div>
      <div class="prl-14"></div>
      <div class="dl-107">У</div>
      <div class="dl-108"></div>
      <div class="prl-15"></div>
      <div class="dl-109">, дана</div>
      <div class="dl-110"></div>
      <div class="dl-111">Ликвидирао,</div>
      <div class="dl-112">Руководилац рачуноводства,</div>
      <div class="dl-113">Налогодавац,</div>
      <div class="prl-16"></div>
      <div class="dl-114"></div>
      <div class="prl-17"></div>
      <div class="prl-18"></div>
      <div class="dl-115"></div>
      <div class="dl-116"></div>
      <div class="prl-19"></div>
      <div class="prl-20"></div>
      <div class="dl-117"></div>
      <div class="dl-118"></div>
      <div class="dl-119"></div>
      <div class="dl-120"></div>
      <div class="prl-21"></div>
      <div class="prl-22"></div>
      <div class="dl-121"></div>
      <div class="dl-122"></div>
      <div class="prl-23"></div>
      <div class="dl-123"></div>
      <div class="dl-124"></div>
    </div>
