<div class="grid-item-container grid-container-right-03">
  <div class="prr-01"></div>
  <div class="prr-02"></div>
  <div class="dr-01">Република Србија</div>
  <div class="dr-02">ОШ "Светозар Марковић" Краљево</div>
  <div class="dr-03">Деловодни број:</div>
  <div class="dr-04"><?php echo $delovodni_broj; ?></div>
  <div class="dr-05">Датум:</div>
  <div class="dr-06"><?php echo $datum_naloga ?></div>
  <div class="dr-07">НАЛОГ ЗА СЛУЖБЕНО ПУТОВАЊЕ</div>
  <div class="prr-03"></div>
  <div class="prr-04"></div>
  <div class="dr-08">Радник/ца</div>
  <div class="dr-09"><?php echo $radnik; ?></div>
  <div class="dr-10">Распоређен/а на послове радног места</div>
  <div class="dr-11"><?php echo $radno_mesto; ?></div>
  <div class="dr-12"></div>
  <div class="dr-13">упућује се на службени пут дана:</div>
  <div class="dr-14"><?php echo $datum_putovanja; ?></div>
  <div class="dr-15">у</div>
  <div class="dr-16"><?php echo $mesto_putovanja; ?></div>
  <div class="dr-17"><?php echo $relacija_putovanja; ?></div>
  <div class="dr-18">Са задатком:</div>
  <div class="dr-19"><?php echo $zadatak_l1; ?></div>
  <div class="dr-20"><?php echo $zadatak_l2; ?></div>
  <div class="dr-21"><?php echo $zadatak_l3; ?></div>
  <div class="dr-22"><?php echo $zadatak_l4; ?></div>
  <div class="dr-23">На службеном путу користи превозно средство</div>
  <div class="dr-24"><?php echo $prevozno_sredstvo; ?></div>
  <div class="dr-25"><?php echo $prevoz_upis; ?></div>
  <div class="prr-05"></div>
  <div class="dr-26">Дневница за ово службено путовање припада у износу од дин.</div>
  <div class="dr-27"><?php echo $dnevnica_iznosi ?></div>
  <div class="dr-28">На службеном путу ће се задржати најдаље до:</div>
  <div class="dr-29"><?php echo $datum_povratka; ?></div>
  <div class="dr-30">године,</div>
  <div class="dr-31">а у року од 48 часова по повратку са службеног пута и доласку на посао, поднеће писмени извештај о
    обављеном</div>
  <div class="dr-32">службеном послу. Рачун о учињеним путним трошковима поднети у року од три дана.</div>
  <div class="prr-06"></div>
  <div class="dr-33">Путни трошкови падају на терет:</div>
  <div class="dr-34"><?php echo $putni_troskovi_l1 ?></div>
  <div class="dr-35"><?php echo $putni_troskovi_l2 ?></div>
  <div class="dr-36"><?php echo $putni_troskovi_l3 ?></div>
  <div class="dr-37"><?php echo $putni_troskovi_l4 ?></div>
  <div class="prr-07"></div>
  <div class="dr-38">Одобравам исплату аконтације у износу од динара</div>
  <div class="dr-39"><?php echo $akontacija; ?></div>
  <div class="prr-08"></div>
  <div class="prr-09"></div>
  <div class="dr-40">Налогодавац,</div>
  <div class="prr-10"></div>
  <div class="dr-41"></div>
  <div class="prr-11"></div>
</div>